# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Hui Cao" # 网站标签页显示的标题
title_separator          : "-"
name                     : &name "Hui Cao" # 您的名字
description              : &description "Associate Professor at Wuhan University of Technology" # 简短描述，用于SEO
url                      : "https://tsaoway.github.io" # 您的网址
baseurl                  : "" # 保持为空
repository               : "tsaoway/tsaoway.github.io" # 您的仓库地址

# Site Author - 侧边栏的个人信息设置
author:
  # Biographic information
  avatar           : "profile.png" # 头像文件名，稍后我们需要把您的照片命名为profile.png放入images文件夹
  name             : "Hui Cao"     # 侧边栏显示的名字
  pronouns         : # 留空
  bio              : "Ph.D. from CityU HK (2017)<br>Assoc. Prof. at WHUT" # 侧边栏简介，支持HTML换行
  location         : "Wuhan, China"
  employer         : "Wuhan University of Technology"
  uri              : # URL
  email            : "iehuicao@whut.edu.cn" # 侧边栏显示的邮箱按钮

  # Academic websites - 学术链接 (把不需要的留空即可)
  academia         : # URL
  arxiv            : # URL
  googlescholar    : "https://scholar.google.com/citations?user=您的ID" # 如果有谷歌学术主页，填在这里
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : # URL
  semantic         : # URL
  ssrn             : # URL
  pubmed           : # URL
  researchgate     : # URL
  scopus           : # URL
  zotero           : # URL


  # Repositories and software development (不需要的留空)
  bitbucket        : # Username
  codepen          : # Username
  dribbble         : # Username
  github           : "tsaoway" # 您的GitHub用户名
  kaggle           : # Username  
  stackoverflow    : # User number
